# frozen_string_literal: true

require "faraday"

# Fetches a page from an external CMS, like WordPress, and extracts the parts
# we need to render it within our own layout: the content and the styles.
#
# We keep only the styles generated by the WordPress block editor. Theme and
# plugin stylesheets are ignored on purpose: they contain global rules, like
# CSS resets, which would break the rest of our layout.
class ExternalPage
  # The first selector that matches wins. WordPress block themes wrap the page
  # content in `.entry-content`.
  CONTENT_SELECTORS = [".entry-content", "main", "body"].freeze

  # WordPress gives every inline stylesheet an id, like
  # `wp-block-columns-inline-css` or `core-block-supports-inline-css`, and
  # serves the block stylesheets it links to from `/wp-includes/`.
  BLOCK_STYLE_ID = /\A(wp-|global-styles|core-block-supports|block-style-variation|classic-theme)/
  BLOCK_STYLESHEET_PATH = %r{/wp-includes/}

  OPEN_TIMEOUT = 5
  TIMEOUT = 10

  def self.fetch(url)
    response = connection.get(url)

    new(response.body, url)
  end

  def self.connection
    Faraday.new(request: { open_timeout: OPEN_TIMEOUT, timeout: TIMEOUT }) do |faraday|
      faraday.response :raise_error
    end
  end

  def initialize(html, url)
    @document = Nokogiri::HTML5.parse(html)
    @url = url
  end

  def content
    @content ||= extract_content
  end

  def styles
    @styles ||= extract_styles
  end

  private

  def extract_content
    node = CONTENT_SELECTORS.lazy.filter_map { |selector| @document.at_css(selector) }.first
    return "" if node.nil?

    remove_scripts(node)
    resolve_urls(node)

    # We keep the wrapping element because its classes are part of the layout.
    node.name == "body" ? node.inner_html : node.to_s
  end

  # We render this HTML within our own page and therefore don't want it to
  # execute any code. The CMS is trusted but it may load third party scripts,
  # like a cookie banner, which we provide ourselves.
  def remove_scripts(node)
    node.css("script, noscript, link, style").each(&:remove)

    node.traverse do |element|
      next unless element.element?

      element.attribute_nodes.each do |attribute|
        attribute.remove if attribute.name.start_with?("on")
      end
    end
  end

  # Relative URLs would point at our own app instead of the CMS.
  def resolve_urls(node)
    node.css("[href], [src], [poster]").each do |element|
      %w[href src poster].each do |attribute|
        value = element[attribute]
        next if value.blank?

        element[attribute] = URI.join(@url, value).to_s
      rescue URI::Error
        next
      end
    end
  end

  def extract_styles
    @document.css("head style, head link[rel='stylesheet']").
      filter_map { |node| node.to_s if block_style?(node) }.
      join("\n")
  end

  def block_style?(node)
    if node.name == "link"
      node["href"].to_s.match?(BLOCK_STYLESHEET_PATH)
    else
      node["id"].to_s.match?(BLOCK_STYLE_ID)
    end
  end
end
