version: "2"
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-1-12"
    config:
      file: ".rubocop.yml"
  scss-lint:
    enabled: true
    checks:
      ImportantRule:
        enabled: false
      VendorPrefix:
        enabled: false
      LeadingZero:
        enabled: false
      PropertySortOrder:
        enabled: false
      StringQuotes:
        enabled: false
      DeclarationOrder:
        enabled: false
      NestingDepth:
        enabled: false

  duplication:
    enabled: true
    exclude_patterns:
    - "db/**"
    - "config/initializers/active_record_postgresql_referential_integrity_patch.rb"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
- "spec/**/*"
- "vendor/**/*"
- "app/assets/javascripts/shared/*"
- "app/assets/javascripts/jquery-migrate-1.0.0.js"
