inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/


# Picks up '.should == x' RSpec syntax
# TODO: convert to '.to eq' syntax?
Lint/Void:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false
