#!/bin/bash
set +e

docker compose down -v --remove-orphans
wait
echo '###########################'
echo 'BEGIN: docker compose build'
echo '###########################'
if [ -n "$1" ]; then
	docker build -f $1 . # Set up the Docker containers
else
	docker compose build # Set up the Docker containers
fi
echo '##############################'
echo 'FINISHED: docker compose build'
echo '##############################'
