#!/bin/bash

# This script runs RuboCop.

echo '----------------------------------------------------'
echo 'BEGIN: docker-compose run web bundle exec rubocop -D'
echo '----------------------------------------------------'
docker-compose run web bundle exec rubocop -D
echo '--------------------------------------------------'
echo 'END: docker-compose run web bundle exec rubocop -D'
echo '--------------------------------------------------'
