#!/bin/bash

# This script runs just the controller tests.

echo '--------------------------------------------------------------'
echo 'BEGIN: docker-compose run web bundle exec rake db:test:prepare'
echo '--------------------------------------------------------------'
docker-compose run web bundle exec rake db:test:prepare
echo '------------------------------------------------------------'
echo 'END: docker-compose run web bundle exec rake db:test:prepare'
echo '------------------------------------------------------------'

echo '----------------------------------------------------------'
echo 'BEGIN: docker-compose run web bundle exec spec/controllers'
echo '----------------------------------------------------------'
docker-compose run web bundle exec rspec spec/controllers
echo '--------------------------------------------------------------'
echo 'END: docker-compose run web bundle exec rspec spec/controllers'
echo '--------------------------------------------------------------'
