---

:verbose: false
:concurrency: 5

:queues:
  - default
  - mailers

# This config is loaded by sidekiq before dotenv is loading our server config.
# Therefore we load the schedule later. See:
#
# - config/initializers/sidekiq.rb
# - config/sidekiq_scheduler.yml
