#!/usr/bin/env sh
#
# Test Stripe API integration and record new cassettes.
# Requires account details in .env.test.local. See [Stripe testing](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Stripe-testing) for details

set -e # Exit if any command fails

git rm spec/fixtures/vcr_cassettes/Stripe-v* -r --ignore-unmatch
./bin/rspec --tag stripe_version

git add spec/fixtures/vcr_cassettes/Stripe-v*
git commit -m "Update Stripe API recordings for new version"
