#!/usr/bin/env sh
#
# Test Stripe API integration and record new cassettes.
# Requires account details in .env.test.local. You can copy from Bitwarden, or [set up a new Stripe account](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-on-an-OFN-instance)

set -e # Exit if any command fails

git rm spec/fixtures/vcr_cassettes/Stripe-v* -r
./bin/rspec --tag stripe_version
