name: Auto Author Assign

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world'
